name: Testing
on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.5
      uses: actions/setup-python@v2
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '3.8.5'
        # Optional - x64 or x86 architecture, defaults to x64
        architecture: 'x64'
    - name: Run Django tests
      run: |
        pip3 install --user django
        python3 -m pip install coverage
        coverage run --source='.' manage.py test
        coverage html -d coverageReport --fail-under=90
    - name: Deploy report page
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./coverageReport
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
